### ISSUE TITLE
Automated me out of a friendship

### ISSUE THREAD

**Issue by dubiousdesigns** [csamp516/spelling-bee-checker#1]
Have you considered the economic and social impact of creating a tool like this?

My good friend (we'll call him `csamp###` for anonymity) often comes to me for help with the last few Spelling Bee words. If he starts using this tool, he'll have no reason to talk to me. I will become extremely lonely. This will also effect my productivity, devastating not only my own economic security, but slashing the margin of my employer. Multiply that over hundreds of millions of people, and you begin to see that this is the kind of tool that can topple nations and destroy civilization.

#EthicalCoding

**Comment by csamp516** [comment]
Maybe you should reply to my slack messages faster, ADAM

#notabug
